version: '3.8'

services:
  web:
    image: odoo:17
    depends_on:
        - db
    container_name: odoodev
    ports:
      - 8069:8069
    volumes:
      - ./volumesOdoo/addons:/mnt/extra-addons
      - ./volumesOdoo/odoo/filestore:/var/lib/odoo/filestore
      - ./volumesOdoo/odoo/sessions:/var/lib/odoo/sessions
    user: root
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: --dev=all

  db:
    image: postgres:15
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./volumesOdoo/dataPostgreSQL:/var/lib/postgresql/data